// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Provides Firebase configuration for the NIT Goa Gate System project
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return windows;
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'LXd3KEvnT4OqwOB-OiAji71f8q3jAJng0HLKslu_V30',
    projectId: 'nit-goa-gate-system',
    messagingSenderId: '788131250494',
    appId: '1:788131250494:web:d21d8ff23ad4624be06c6f',
    // Leave these empty for desktop only - they're for web/mobile
    authDomain: '',
    databaseURL: '',
    storageBucket: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'LXd3KEvnT4OqwOB-OiAji71f8q3jAJng0HLKslu_V30',
    projectId: 'nit-goa-gate-system',
    messagingSenderId: '788131250494',
    appId: '1:788131250494:android:c0e60820a2417134e06c6f',
    databaseURL: '',
    storageBucket: 'nit-goa-gate-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'LXd3KEvnT4OqwOB-OiAji71f8q3jAJng0HLKslu_V30',
    projectId: 'nit-goa-gate-system',
    messagingSenderId: '788131250494',
    appId: '1:788131250494:ios:8ba17a0784881d14e06c6f',
    databaseURL: '',
    storageBucket: 'nit-goa-gate-system.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'LXd3KEvnT4OqwOB-OiAji71f8q3jAJng0HLKslu_V30',
    projectId: 'nit-goa-gate-system',
    messagingSenderId: '788131250494',
    appId: '1:788131250494:ios:8ba17a0784881d14e06c6f',
    databaseURL: '',
    storageBucket: 'nit-goa-gate-system.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'LXd3KEvnT4OqwOB-OiAji71f8q3jAJng0HLKslu_V30',
    projectId: 'nit-goa-gate-system',
    messagingSenderId: '788131250494',
    appId: '1:788131250494:web:d21d8ff23ad4624be06c6f',
    authDomain: 'nit-goa-gate-system.firebaseapp.com',
    databaseURL: 'https://nit-goa-gate-system.firebasedatabase.app',
    storageBucket: 'nit-goa-gate-system.appspot.com',
  );
}
